module.exports={
    configurewebpack:{
        resolve:{
            alias:{
                'assets':'@/assets',
                'common':'@/common',
                'commponents':'@/commponents',
                'network':'@/network',
                'views':'@/views',
            }
        }
    }
}